/******************************************************************************/
/* SGBD: MariaDB v10.11.13-0ubuntu0.24.04.1                                   */
/* Base de datos: BDD_BANCO_EC                                                */
/* Script pra la administracion de un sistema bancario                        */
/* BaseDatos.sql - MariaDB                                                    */
/******************************************************************************/

DROP DATABASE IF EXISTS BDD_BANCO_EC;
CREATE DATABASE BDD_BANCO_EC CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE BDD_BANCO_EC;

-- ============================
-- Tabla: BEC_CUSTOMER
-- ============================
DROP TABLE IF EXISTS BEC_CUSTOMER;
CREATE TABLE BEC_CUSTOMER (
  ID_CUSTOMER CHAR(36) NOT NULL DEFAULT (UUID()), -- (PK)
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  IDENTIFICATION VARCHAR(13) NOT NULL, -- (UK)
  ADDRESS VARCHAR(255),
  PHONE VARCHAR(10),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_BEC_CUSTOMER PRIMARY KEY (ID_CUSTOMER),
  CONSTRAINT UK_BEC_CUSTOMER_IDENTIFICATION UNIQUE (IDENTIFICATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_BEC_CUSTOMER_NAME ON BEC_CUSTOMER (LAST_NAME, FIRST_NAME);

-- ============================
-- Tabla: BEC_ACCOUNT
-- ============================
DROP TABLE IF EXISTS BEC_ACCOUNT;
CREATE TABLE BEC_ACCOUNT (
  ID_ACCOUNT CHAR(36) NOT NULL DEFAULT (UUID()), -- (PK)
  ACCOUNT_NUMBER VARCHAR(32) NOT NULL, -- (UK)
  ACCOUNT_TYPE VARCHAR(20) NOT NULL, -- 'AHORRO, CORRIENTE'
  BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0.00, -- Initial Balance and Current Balance
  STATUS TINYINT(1) NOT NULL DEFAULT 1,
  CUSTOMER_ID CHAR(36) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_BEC_ACCOUNT PRIMARY KEY (ID_ACCOUNT),
  CONSTRAINT UK_BEC_ACCOUNT_ACCOUNT_NUMBER UNIQUE (ACCOUNT_NUMBER),
  CONSTRAINT FK_BEC_ACCOUNT_BEC_CUSTOMER FOREIGN KEY (CUSTOMER_ID) 
    REFERENCES BEC_CUSTOMER(ID_CUSTOMER) ON DELETE CASCADE,
  CONSTRAINT CHK_BEC_ACCOUNT_BALANCE CHECK (BALANCE >= 0),
  CONSTRAINT CHK_BEC_ACCOUNT_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('AHORRO','CORRIENTE')),
  CONSTRAINT CHK_BEC_ACCOUNT_STATUS CHECK (STATUS IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_BEC_ACCOUNT_CUSTOMER_ID ON BEC_ACCOUNT (CUSTOMER_ID);

-- ============================
-- Tabla: BEC_TRANSACTION
-- ============================
DROP TABLE IF EXISTS BEC_TRANSACTION;
CREATE TABLE BEC_TRANSACTION (
  ID_TRANSACTION CHAR(36) NOT NULL DEFAULT (UUID()), -- (PK)
  ACCOUNT_ID CHAR(36) NOT NULL,
  TYPE VARCHAR(10) NOT NULL, -- 'CREDIT' or 'DEBIT'
  AMOUNT DECIMAL(18,2) NOT NULL, -- Amount to Transfer
  BALANCE_BEFORE DECIMAL(18,2) NOT NULL,
  BALANCE_AFTER DECIMAL(18,2) NOT NULL,
  DESCRIPTION VARCHAR(150),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_BEC_TRANSACTION PRIMARY KEY (ID_TRANSACTION),
  CONSTRAINT FK_BEC_TRANSACTION_BEC_ACCOUNT FOREIGN KEY (ACCOUNT_ID) 
    REFERENCES BEC_ACCOUNT(ID_ACCOUNT) ON DELETE CASCADE,
  CONSTRAINT CHK_BEC_TRANSACTION_TYPE CHECK (TYPE IN ('CREDIT','DEBIT')),
  CONSTRAINT CHK_BEC_TRANSACTION_AMOUNT CHECK (AMOUNT > 0),
  CONSTRAINT CHK_BEC_TRANSACTION_BALANCE_BEFORE CHECK (BALANCE_BEFORE >= 0),
  CONSTRAINT CHK_BEC_TRANSACTION_BALANCE_AFTER CHECK (BALANCE_AFTER >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_BEC_TRANSACTION_ACCOUNT_ID ON BEC_TRANSACTION (ACCOUNT_ID);
CREATE INDEX IDX_BEC_TRANSACTION_CREATED_AT ON BEC_TRANSACTION (CREATED_AT);

-- ============================
-- Tabla: BEC_USER
-- ============================
DROP TABLE IF EXISTS BEC_USER;
CREATE TABLE BEC_USER (
  ID_USER CHAR(36) NOT NULL DEFAULT (UUID()),
  USERNAME VARCHAR(20) NOT NULL,
  PASSWORD_HASH VARCHAR(50) NOT NULL,
  ROLES JSON NULL, -- e.g. ["USER","ADMIN"]
  CUSTOMER_ID CHAR(36) NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_BEC_USER PRIMARY KEY (ID_USER),
  CONSTRAINT UK_BEC_USER_USERNAME UNIQUE (USERNAME),
  CONSTRAINT FK_BEC_USER_BEC_CUSTOMER FOREIGN KEY (CUSTOMER_ID) 
    REFERENCES BEC_CUSTOMER(ID_CUSTOMER) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_BEC_USER_CUSTOMER_ID ON BEC_USER (CUSTOMER_ID);


