openapi: 3.0.3
info:
  title: Transaction Service API
  version: 1.0.0
servers:
  - url: http://localhost:8084/api
paths:
  /transaction/create:
    post:
      tags:
        - Create Transaction
      summary: Registrar transacción (CREDIT o DEBIT)
      operationId: PostTransactionCreateRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionInput'
      responses:
        '201':
          description: Transacción registrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionOutput'
        '400':
          description: Error en la transacción
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /transactions/filter:
    get:
      tags:
        - List Transactions
      summary: Listar transacciones
      operationId: GetTransactionsListByAccoundIdAndDateResponse
      parameters:
        - in: query
          name: accountId
          schema:
            type: string
            format: uuid
        - in: query
          name: startDate
          schema:
            type: string
            format: date
        - in: query
          name: endDate
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Lista de transacciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionOutput'
  /transaction/{transactionId}:
    get:
      tags:
        - Get Transaction by TransactionId
      summary: Obtener transacción por TransactionId
      operationId: GetTransactionByTransactionIdResponse
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
            format: uuid
          required: true
          description: Identificador único de la transacción (UUID)
      responses:
        '200':
          description: Transacción encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionOutput'
        '404':
          description: Transacción no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

  /transactions:
    get:
      tags:
        - List Transactions
      summary: Listar Transacciones
      operationId: GetTransactionsListResponse
      responses:
        '200':
          description: Transacciones encontradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionOutput'

components:
  schemas:
    TransactionInput:
      type: object
      required:
        - accountId
        - type
        - amount
      properties:
        accountId:
          type: string
          format: uuid
          description: "Identificador único de la cuenta (UUID)."
        type:
          type: string
          enum: [CREDIT, DEBIT]
          description: "Tipo de transacción. Puede ser CREDIT o DEBIT."
        amount:
          type: number
          format: decimal
          description: "Monto de la transacción."
        description:
          type: string
          maxLength: 150
          description: "Descripción de la transacción. Máximo 150 caracteres."

    TransactionOutput:
      type: object
      required:
        - idTransaction
        - accountId
        - type
        - amount
        - balanceBefore
        - balanceAfter
        - description
        - createdAt
      properties:
        idTransaction:
          type: string
          format: uuid
          description: "Identificador único de la transacción (UUID)."
          example: "e1f2g3h4-i5j6-7890-klmn-1234567890ab"
        accountId:
          type: string
          format: uuid
          description: "Identificador único de la cuenta (UUID)."
          example: "a1b2c3d4-e5f6-7890-abcd-1234567890ab"
        type:
          type: string
          enum: [CREDIT, DEBIT]
          description: "Tipo de transacción. Puede ser CREDIT o DEBIT."
          example: "CREDIT"
        amount:
          type: number
          format: decimal
          description: "Monto de la transacción."
          example: 500.00
        balanceBefore:
          type: number
          format: decimal
          description: "Saldo antes de la transacción."
          example: 1000.00
        balanceAfter:
          type: number
          format: decimal
          description: "Saldo después de la transacción."
          example: 1500.00
        description:
          type: string
          maxLength: 150
          description: "Descripción de la transacción. Máximo 150 caracteres."
          example: "Depósito en efectivo"
        createdAt:
          type: string
          format: date-time
          readOnly: true
          description: "Fecha de creación de la transacción."
          example: "2025-09-28T10:15:30Z"
        account:
          $ref: '#/components/schemas/AccountSummary'

    MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: "La transacción fue procesada correctamente."

    AccountSummary:
      type: object
      description: "Resumen embebido del cuenta (solo lectura)."
      properties:
        idAccount:
          type: string
          format: uuid
          readOnly: true
          description: "Identificador único de la cuenta (UUID)."
          example: "a1b2c3d4-e5f6-7890-abcd-1234567890ab"
        accountNumber:
          type: string
          maxLength: 32
          readOnly: true
          description: "Número de cuenta. Único. Máximo 32 caracteres."
          example: "1234567890123456"
        accountType:
          type: string
          enum: [AHORRO, CORRIENTE]
          readOnly: true
          description: "Tipo de cuenta. Puede ser AHORRO o CORRIENTE."
          example: "AHORRO"
        balance:
          type: number
          format: decimal
          readOnly: true
          description: "Saldo actual de la cuenta."
          example: 1000.50
        status:
          type: integer
          enum: [0,1]
          readOnly: true
          description: "Estado de la cuenta. 1=Activa, 0=Inactiva."
          example: 1
        customerId:
          type: string
          format: uuid
          readOnly: true
          description: "Identificador único del cliente (UUID)."
          example: "b7e6a2e2-8c2e-4e2a-9e2a-123456789abc"
        createdAt:
          type: string
          format: date-time
          readOnly: true
          description: "Fecha de creación de la cuenta."
          example: "2025-09-28T10:15:30Z"
        updatedAt:
          type: string
          format: date-time
          readOnly: true
          description: "Fecha de última actualización de la cuenta."
          example: "2025-09-28T12:00:00Z"
